// ./src/parser/blif_parser.cpp generated by reflex 1.0.9 from ./src/parser/blif_parser.l

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define bl_REFLEX_OPTION_fast                true
#define bl_REFLEX_OPTION_header_file         ./include/parser/blif_parser.h
#define bl_REFLEX_OPTION_lex                 bl_lex
#define bl_REFLEX_OPTION_lexer               BL_LEXER
#define bl_REFLEX_OPTION_namespace           blifparser
#define bl_REFLEX_OPTION_outfile             ./src/parser/blif_parser.cpp
#define bl_REFLEX_OPTION_prefix              bl_

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top{ user code %}                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 12 "./src/parser/blif_parser.l"

#include "circuit.h"
using namespace nodecircuit;


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace blifparser {

class BL_LEXER : public reflex::AbstractLexer<reflex::Matcher> {
#line 17 "./src/parser/blif_parser.l"

Node* current_node;
NodeVector cur_nodes;
int mode;
virtual int wrap() { return 1; }
public:
Circuit* circuit;

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  BL_LEXER(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
#line 26 "./src/parser/blif_parser.l"

circuit = NULL;
current_node = NULL;
mode = 255; // 128:start 129:output 130:input 131:gate 132:value 254:nothing 255:finish

  }
  static const int INITIAL = 0;
  virtual int bl_lex();
  int bl_lex(
      const reflex::Input& input,
      std::ostream        *os = NULL)
  {
    in(input);
    if (os)
      out(*os);
    return bl_lex();
  }
};

} // namespace blifparser

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "./src/parser/blif_parser.l"
// simple blif parser, without error recover, and without comment detection


#include <cstdio>
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
using namespace std;



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace blifparser {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace blifparser

int blifparser::BL_LEXER::bl_lex()
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return 0;
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 47: (?:\Q.end\E)
#line 47 "./src/parser/blif_parser.l"
mode = 255;
            break;
          case 2: // rule at line 48: (?:\Q.model\E)
#line 48 "./src/parser/blif_parser.l"
mode = 128;
            break;
          case 3: // rule at line 49: (?:\Q.outputs\E)
#line 49 "./src/parser/blif_parser.l"
mode = 129;
            break;
          case 4: // rule at line 50: (?:\Q.inputs\E)
#line 50 "./src/parser/blif_parser.l"
mode = 130;
            break;
          case 5: // rule at line 51: (?:\Q.names\E)
#line 51 "./src/parser/blif_parser.l"
{
              mode = 131;
              cur_nodes.clear();
            }


            break;
          case 6: // rule at line 57: (?:[A-Za-z][0-9A-Z_a-z]*(?:(?:\Q[\E)[0-9]+(?:\Q]\E))*)
#line 57 "./src/parser/blif_parser.l"
switch (mode) {
          case 128:
            circuit->name = text();
            mode = 254;
            break;
          case 129:
            current_node = new BlifNode;
            current_node->name = text();
            current_node->is_output = true;
            circuit->outputs.push_back(current_node);
            circuit->all_nodes.push_back(current_node);
            circuit->all_nodes_map[current_node->name] = current_node;
            break;
          case 130:
            current_node = new BlifNode;
            current_node->name = text();
            current_node->is_input = true;
            circuit->inputs.push_back(current_node);
            circuit->all_nodes.push_back(current_node);
            circuit->all_nodes_map[current_node->name] = current_node;
            break;
          case 131:
            current_node = circuit->GetNode(string(text()));
            if (!current_node) {
              current_node = new BlifNode;
              current_node->name = text();
              circuit->all_nodes.push_back(current_node);
              circuit->all_nodes_map[current_node->name] = current_node;
            }
            cur_nodes.push_back(current_node);
            break;
        }

            break;
          case 7: // rule at line 90: (?:(?:[01])(?:\r?\n)|(?:[\x2d01][\x2d01]+)(?:[\x20])(?:[01])(?:\r?\n)|(?:[01])(?:[\x20])(?:[01])(?:\r?\n))
#line 90 "./src/parser/blif_parser.l"
if (cur_nodes.size() == 0)
          mode = 254;
        else {
          if (mode == 131) {
            current_node = cur_nodes[cur_nodes.size()-1];
            for (int i = 0; i < cur_nodes.size()-1; i++) {
              Node* node = cur_nodes[i];
              current_node->inputs.push_back(node);
              node->outputs.push_back(current_node);
            }
            mode = 132;
          }
          if (mode = 132) {
            string str(text());
            while (str[str.size()-1] == '\n' || str[str.size()-1] == '\r')
              str.resize(str.size()-1);
            ((BlifNode*)current_node)->str_values.push_back(str);
          }
        }

            break;
          case 8: // rule at line 110: .
#line 110 "./src/parser/blif_parser.l"
mode=mode;

            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

namespace blifparser {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c0 = 0, c1 = c0;
  m.FSM_INIT(c1);

S0:
  c0 = c1, c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S15;
  if ('A' <= c1 && c1 <= 'Z') goto S15;
  if ('0' <= c1 && c1 <= '1') goto S22;
  if (c1 == '.') goto S8;
  if (c1 == '-') goto S29;
  if ('\v' <= c1) goto S33;
  if ('\n' <= c1) return m.FSM_HALT(c1);
  if ('\0' <= c1 && c1 <= '\t') goto S33;
  return m.FSM_HALT(c1);

S8:
  m.FSM_TAKE(8);
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S39;
  if (c1 == 'n') goto S43;
  if (c1 == 'm') goto S37;
  if (c1 == 'i') goto S41;
  if (c1 == 'e') goto S35;
  return m.FSM_HALT(c1);

S15:
  m.FSM_TAKE(6);
  c0 = c1, c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S45;
  if (c1 == '_') goto S45;
  if (c1 == '[') goto S52;
  if ('A' <= c1 && c1 <= 'Z') goto S45;
  if ('0' <= c1 && c1 <= '9') goto S45;
  return m.FSM_HALT(c1);

S22:
  m.FSM_TAKE(8);
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S60;
  if (c1 == '-') goto S60;
  if (c1 == ' ') goto S56;
  if (c1 == '\r') goto S58;
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S29:
  m.FSM_TAKE(8);
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S60;
  if (c1 == '-') goto S60;
  return m.FSM_HALT(c1);

S33:
  m.FSM_TAKE(8);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S35:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S64;
  return m.FSM_HALT(c1);

S37:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S66;
  return m.FSM_HALT(c1);

S39:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S68;
  return m.FSM_HALT(c1);

S41:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S70;
  return m.FSM_HALT(c1);

S43:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'a') goto S72;
  return m.FSM_HALT(c1);

S45:
  m.FSM_TAKE(6);
  c0 = c1, c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S45;
  if (c1 == '_') goto S45;
  if (c1 == '[') goto S52;
  if ('A' <= c1 && c1 <= 'Z') goto S45;
  if ('0' <= c1 && c1 <= '9') goto S45;
  return m.FSM_HALT(c1);

S52:
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S74;
  return m.FSM_HALT(c1);

S54:
  m.FSM_TAKE(7);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S56:
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S77;
  return m.FSM_HALT(c1);

S58:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S60:
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S60;
  if (c1 == '-') goto S60;
  if (c1 == ' ') goto S80;
  return m.FSM_HALT(c1);

S64:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'd') goto S82;
  return m.FSM_HALT(c1);

S66:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'd') goto S84;
  return m.FSM_HALT(c1);

S68:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 't') goto S86;
  return m.FSM_HALT(c1);

S70:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S88;
  return m.FSM_HALT(c1);

S72:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S90;
  return m.FSM_HALT(c1);

S74:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == ']') goto S92;
  if ('0' <= c1 && c1 <= '9') goto S74;
  return m.FSM_HALT(c1);

S77:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '\r') goto S95;
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S80:
  c0 = c1, c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S97;
  return m.FSM_HALT(c1);

S82:
  m.FSM_TAKE(1);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S84:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S100;
  return m.FSM_HALT(c1);

S86:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S102;
  return m.FSM_HALT(c1);

S88:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S104;
  return m.FSM_HALT(c1);

S90:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S106;
  return m.FSM_HALT(c1);

S92:
  m.FSM_TAKE(6);
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '[') goto S52;
  return m.FSM_HALT(c1);

S95:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S97:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '\r') goto S108;
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S100:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S110;
  return m.FSM_HALT(c1);

S102:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S112;
  return m.FSM_HALT(c1);

S104:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 't') goto S114;
  return m.FSM_HALT(c1);

S106:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 's') goto S116;
  return m.FSM_HALT(c1);

S108:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == '\n') goto S54;
  return m.FSM_HALT(c1);

S110:
  m.FSM_TAKE(2);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S112:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 't') goto S118;
  return m.FSM_HALT(c1);

S114:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 's') goto S120;
  return m.FSM_HALT(c1);

S116:
  m.FSM_TAKE(5);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S118:
  c0 = c1, c1 = m.FSM_CHAR();
  if (c1 == 's') goto S122;
  return m.FSM_HALT(c1);

S120:
  m.FSM_TAKE(4);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);

S122:
  m.FSM_TAKE(3);
  c0 = c1, c1 = m.FSM_CHAR();
  return m.FSM_HALT(c1);
}

} // namespace blifparser
